# Generated by Django 3.2 on 2021-04-19 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagegallery', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menucollection',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodsubtype',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food'),
        ),
        migrations.AddField(
            model_name='foodsubtype',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.subtype'),
        ),
        migrations.AddField(
            model_name='food',
            name='MenuCollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucollection'),
        ),
        migrations.AddField(
            model_name='food',
            name='addons',
            field=models.ManyToManyField(to='restaurant.Addons'),
        ),
        migrations.AddField(
            model_name='food',
            name='cover_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegallery.image'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
