# Generated by Django 3.2 on 2021-07-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
