# Generated by Django 3.2 on 2021-04-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storemanagerapp', '0002_auto_20210422_1302'),
        ('restaurant', '0003_auto_20210422_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storemanagerapp.storemanagerbasicdetial'),
        ),
        migrations.AlterField(
            model_name='menucollection',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storemanagerapp.storemanagerbasicdetial'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storemanagerapp.storemanagerbasicdetial'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storemanagerapp.storemanagerbasicdetial'),
        ),
    ]
