# Generated by Django 3.2 on 2021-05-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210428_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='MenuCollection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucollection'),
        ),
    ]
