# Generated by Django 3.2 on 2021-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_addons_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='subtypes',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.FoodSubType'),
        ),
    ]
