# Generated by Django 3.2 on 2021-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210420_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amountInCents',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
