# Generated by Django 3.2 on 2021-04-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210420_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amountInCents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
