# Generated by Django 3.2 on 2021-04-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0001_initial'),
        ('restaurant', '0005_alter_food_amountincents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amountInCents',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagegallery.image'),
        ),
    ]
