# Generated by Django 3.2 on 2021-05-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storemanagerapp', '0001_initial'),
        ('imagegallery', '0001_initial'),
        ('restaurant', '0005_addons_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amountInCents', models.IntegerField(null=True)),
                ('addons', models.ManyToManyField(to='restaurant.Addons')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagegallery.image')),
                ('foods', models.ManyToManyField(to='restaurant.Food')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storemanagerapp.storemanagerbasicdetail')),
            ],
        ),
    ]
