# Generated by Django 3.2 on 2021-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_foodcombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='amountInCents',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='amountInCents',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodcombo',
            name='amountInCents',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsubtype',
            name='amountInCents',
            field=models.FloatField(),
        ),
    ]
