# Generated by Django 3.0.5 on 2021-04-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_auto_20210422_1243'),
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.IntegerField(blank=True, null=True)),
                ('orderTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Ordered'), (2, 'Picked Up'), (3, 'Delivering'), (4, 'Delivered')], default=1, max_length=200)),
                ('foodOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.FoodOrder')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicapp.Location')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
