# Generated by Django 3.2 on 2021-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.IntegerField(blank=True, null=True)),
                ('orderTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Ordered'), (2, 'Picked Up'), (3, 'Delivering'), (4, 'Delivered')], default=1)),
            ],
        ),
    ]
