# Generated by Django 3.2 on 2021-07-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.IntegerField(blank=True, null=True)),
                ('orderTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Ordered'), (2, 'Picked Up'), (3, 'Delivering'), (4, 'Delivered')], default=1)),
                ('foodOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.foodorder')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicapp.location')),
            ],
        ),
    ]
