# Generated by Django 3.2 on 2021-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ordered'), (2, 'Picked Up'), (3, 'Delivering'), (4, 'Delivered')], default=1),
        ),
    ]
