# Generated by Django 3.2 on 2021-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210422_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ordered'), (2, 'Picked Up'), (3, 'Delivering'), (4, 'Delivered')], default=1, max_length=200),
        ),
    ]
