# Generated by Django 3.2.4 on 2021-07-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('restaurant', '0005_addons_manager'),
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foodOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(null=True, to='restaurant.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.user'),
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
    ]
