# Generated by Django 3.2 on 2021-04-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20210420_0820'),
        ('storemanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanagerbasicdetial',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicapp.location'),
        ),
    ]
