# Generated by Django 3.2.4 on 2021-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanagerbasicdetail',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
