# Generated by Django 3.2 on 2021-04-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemanagerapp', '0002_alter_storemanagerbasicdetial_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanagerbasicdetial',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='storemanagerbasicdetial',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
